# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amor', models.PositiveIntegerField(default=0)),
                ('ira', models.PositiveIntegerField(default=0)),
                ('alegria', models.PositiveIntegerField(default=0)),
                ('sorpresa', models.PositiveIntegerField(default=0)),
                ('envidia', models.PositiveIntegerField(default=0)),
                ('tristeza', models.PositiveIntegerField(default=0)),
                ('miedo', models.PositiveIntegerField(default=0)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happy.Tweet')),
            ],
        ),
    ]
