# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0002_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='tweet',
        ),
        migrations.AddField(
            model_name='measure',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='happy.City'),
        ),
    ]
