# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0003_auto_20161111_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='measure',
            new_name='Measur',
        ),
    ]
